root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project:
    - ./tsconfig.eslint.json
    - ./packages/*/tsconfig.json
  ecmaFeatures:
    jsx: true
  useJSXTextNode: true

settings:
  import/parsers:
    '@typescript-eslint/parser': [.ts, .tsx]
  import/resolver:
    node:
      extensions: [.js, .jsx, .ts, .tsx]
    typescript:
      project: packages/*/tsconfig.json
      extensions: [.js, .jsx, .ts, .tsx]

  react:
    version: detect

plugins:
  - '@typescript-eslint'
  - import
  - vitest

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier # this to be added to last
rules:
  '@typescript-eslint/no-namespace': 'off'
  import/prefer-default-export: 'off'
  import/no-extraneous-dependencies: 'off'
